// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.Data;

#nullable disable

namespace UserService.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20250817210347_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserService.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "İstanbul, Türkiye",
                            CreatedAt = new DateTime(2025, 8, 17, 21, 3, 47, 275, DateTimeKind.Utc).AddTicks(1258),
                            Email = "ahmet@example.com",
                            IsActive = true,
                            Name = "Ahmet Yılmaz",
                            PhoneNumber = "+90 555 123 4567",
                            UserType = 0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Abdullahazam Cd. NO:28/A, Huzur Mahallesi, 34773 Ümraniye/İstanbul",
                            CompanyName = "ABC Elektronik Ltd. Şti.",
                            CreatedAt = new DateTime(2025, 8, 17, 21, 3, 47, 275, DateTimeKind.Utc).AddTicks(1261),
                            Email = "info@abcelektronik.com",
                            IsActive = true,
                            Name = "ABC Elektronik Ltd. Şti.",
                            PhoneNumber = "+90 212 555 0123",
                            UserType = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "Abdullahazam Cd. NO:28/A, Huzur Mahallesi, 34773 Ümraniye/İstanbul",
                            CompanyName = "Ruby Elektronik",
                            CreatedAt = new DateTime(2025, 8, 17, 21, 3, 47, 275, DateTimeKind.Utc).AddTicks(1263),
                            Email = "hasanhuseyinyakut@gmail.com",
                            IsActive = true,
                            Name = "Ruby Elektronik",
                            PhoneNumber = "+90 546 944 33 88",
                            UserType = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
